# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"
# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				experience_bottle = true
				camel = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				mooshroom = true
				llama_spit = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				block_display = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				snow_golem = true
				cod = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wither_skeleton = true
				vex = true
				wandering_trader = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				ominous_item_spawner = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.xercapaint]
				canvas = true
				easel = true

			[light_sources.settings.entities.alexsmobsup]
				devils_hole_pupfish = true
				kangaroo = true
				blue_jay = true
				skelewag = true
				bone_serpent_part = true
				catfish = true
				fart = true
				tasmanian_devil = true
				centipede_tail = true
				cosmic_cod = true
				rhinoceros = true
				comb_jelly = true
				vine_lasso = true
				mungus = true
				jerboa = true
				skunk = true
				dropbear = true
				bunfungus = true
				rattlesnake = true
				blobfish = true
				mimicube = true
				snow_leopard = true
				moose = true
				tiger = true
				rocky_roller = true
				rain_frog = true
				cosmaw = true
				mosquito_spit = true
				stradpole = true
				spectre = true
				hemolymph = true
				anaconda = true
				hammerhead_shark = true
				sunbird = true
				triops = true
				gazelle = true
				sea_bear = true
				tarantula_hawk = true
				void_worm_part = true
				void_worm_shot = true
				void_portal = true
				enderiophage = true
				terrapin = true
				platypus = true
				murmur = true
				void_worm = true
				bald_eagle = true
				centipede_body = true
				froststalker = true
				fly = true
				toucan = true
				skreecher = true
				cachalot_whale = true
				tossed_item = true
				bison = true
				pollen_ball = true
				mudskipper = true
				mud_ball = true
				gelada_monkey = true
				murmur_head = true
				cachalot_echo = true
				laviathan = true
				anteater = true
				enderiophage_rocket = true
				endergrade = true
				roadrunner = true
				cockroach_egg = true
				leafcutter_ant = true
				shoebill = true
				lobster = true
				grizzly_bear = true
				squid_grapple = true
				potoo = true
				farseer = true
				centipede_head = true
				flutter = true
				orca = true
				tendon_segment = true
				ice_shard = true
				maned_wolf = true
				crow = true
				banana_slug = true
				elephant = true
				crocodile = true
				crimson_mosquito = true
				sand_shot = true
				seal = true
				straddler = true
				emu = true
				mimic_octopus = true
				soul_vulture = true
				warped_mosco = true
				guster = true
				caiman = true
				tusklin = true
				underminer = true
				anaconda_part = true
				emu_egg = true
				gorilla = true
				flying_fish = true
				capuchin_monkey = true
				cockroach = true
				komodo_dragon = true
				bone_serpent = true
				mantis_shrimp = true
				seagull = true
				raccoon = true
				alligator_snapping_turtle = true
				giant_squid = true
				hummingbird = true
				straddleboard = true
				warped_toad = true
				frilled_shark = true
				shark_tooth_arrow = true
				sugar_glider = true
				gust = true

			[light_sources.settings.entities.simulated]
				launched_plunger = true
				honey_glue = true
				contraption_diagram = true

			[light_sources.settings.entities.enderscape]
				rustle = true
				rubblemite = true
				drifter = true
				driftlet = true

			[light_sources.settings.entities.amendments]
				medium_dragon_fireball = true
				falling_lantern = true
				medium_fireball = true

			[light_sources.settings.entities.redomesticate]
				highlighted_block = true
				feather = true
				recall_ball = true
				giant_bubble = true
				psychic_wall = true
				chain_lightning = true
				following_jukebox = true

			[light_sources.settings.entities.cold_sweat]
				chameleon = true

			[light_sources.settings.entities.aeronautics]
				propeller_bearing_contraption = true
				gust = true

			[light_sources.settings.entities.cyberspace]
				cyberspace_rift = true
				darknet_rift_2 = true
				cyberspace_rift_2 = true
				data_entity = true
				darknet_rift = true
				obligator = true
				darknet_rupture = true

			[light_sources.settings.entities.exposure]
				glass_photograph_frame = true
				camera_stand = true
				photograph_frame = true

			[light_sources.settings.entities.incision]
				purgerpuke = true
				purger = true
				seer = true
				skeletoncultist = true

			[light_sources.settings.entities.little_big_redstone]
				sticky_note = true

			[light_sources.settings.entities.simpleradio]
				wire = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true
				slingshot_projectile = true
				brick_projectile = true
				plunderer = true
				falling_sack = true
				pearl_marker = true
				hat_stand = true
				bomb = true
				falling_ash = true
				falling_urn = true
				cannonball = true
				red_merchant = true
				cannon_boat = true
				rope_arrow = true
				slimeball_projectile = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				seat = true
				stationary_contraption = true
				package = true
				contraption = true
				gantry_contraption = true
				super_glue = true
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.offroad]
				borehead_contraption_entity = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
