#Which fluids should be blacklisted? This isn't retroactive.
#Empty by default. Water cannot be blacklisted.
fluid_blacklist = []
#Which blocks should be blacklisted? This isn't retroactive.
#Only applies to SimpleWaterLoggableBlock variants (stairs, slabs, etc.).
block_blacklist = []
#Should fluidlogged blocks emit the higher of blocklight and fluid light?
#Significant performance penalty.
consider_fluid_light = true
#Can partial fluid blocks waterlog (WIP)
flowing_fluids_log = false
#Should we force chunk updates (resolves sync issues, but may cause stability problems)
force_chunk_updates = false
